name: 'Workflow Dispatcher with Polling'
description: 'Dispatch a GitHub workflow and poll for its completion status.'

inputs:
  token:
    description: 'GitHub token with repository permissions.'
    required: true
  repository:
    description: 'The repository in the format "owner/repo".'
    required: true
  workflow:
    description: 'The workflow file name to dispatch (e.g., "my-workflow.yml").'
    required: true
  ref:
    description: 'The branch or tag to run the workflow on.'
    required: true
  inputs:
    description: 'Optional JSON string of inputs to pass to the workflow.'
    required: false
  startTime:
    description: 'The number of seconds to wait before starting the polling.'
    required: false
    default: '0'
  interval:
    description: 'Polling interval in seconds. Default is 5 seconds.'
    required: false
    default: '5'
  timeout:
    description: 'Timeout for polling in seconds. Default is 300 seconds (5 minutes).'
    required: false
    default: '300'

runs:
  using: 'node20'
  main: 'dist/index.js'

author: 'ophirharamaty@gmail.com'
branding:
  icon: 'zap'
  color: 'blue'
