name: 'Workflow Dispatcher with Polling'
description: 'Dispatch a GitHub workflow and poll for its completion status.'

inputs:
  token:
    description: 'GitHub token with repository permissions.'
    required: true
  repository:
    description: 'The repository in the format "owner/repo".'
    required: true
  workflow:
    description: 'The workflow file name to dispatch (e.g., "my-workflow.yml").'
    required: true
  ref:
    description: 'The branch or tag to run the workflow on.'
    required: true
  inputs:
    description: 'Optional JSON string of inputs to pass to the workflow.'
    required: false
  startTime:
    description: 'The start time for monitoring workflow runs (ISO 8601 format). Defaults to the current time.'
    required: false
    default: ''
  interval:
    description: 'Polling interval in milliseconds. Default is 5000ms (5 seconds).'
    required: false
    default: '5000'
  timeout:
    description: 'Timeout for polling in milliseconds. Default is 300000ms (5 minutes).'
    required: false
    default: '300000'

runs:
  using: 'node20'
  main: 'dist/index.js'

author: 'ophirharamaty@gmail.com'
branding:
  icon: 'zap'
  color: 'blue'
