name: Dispatched Workflow
on:
  workflow_dispatch:
    inputs:
        uuid:
          type: string
          description: "UUID to identify workflow run"
          required: true

jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        run: 'echo "Inputs: ${{toJson(inputs)}}"'
        shell: bash

      - name: Wait
        run: sleep 20

      - name: Succeed
        run: exit 0