name: Dispatched Workflow
on:
  workflow_dispatch:
    inputs:
        uuid:
          type: string
          description: "UUID to identify workflow run"
          required: true

jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        run: echo ${{toJson(inputs)}}
        shell: bash