name: Fast Failing Dispatched Workflow
on:
  workflow_dispatch:
    inputs:
        uuid:
          type: string
          description: "UUID to identify workflow run"
          required: true

jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        uses: universal-actions/identify-workflow@v1

      - name: Wait
        run: sleep 1

      - name: Fail
        run: exit 1
