name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-slow-succeeding-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Slow Succeeding Workflow
        uses: ./
        with:
          token: ${{ secrets.SINGING_STAGE_WORKFLOW_TOKEN }}
          repository: ${{ github.repository }}
          workflow: dispatched-slow-succeeding-workflow.yml
          ref: main

          inputs: |
            {
              "uuid": "${{ github.sha }}-1"
            }

  run-fast-failing-workflow:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Fast Failing Workflow
        uses: ./
        with:
          token: ${{ secrets.SINGING_STAGE_WORKFLOW_TOKEN }}
          repository: ${{ github.repository }}
          workflow: dispatched-fast-failing-workflow.yml
          ref: main

          inputs: |
            {
              "uuid": "${{ github.sha }}-2"
            }
 validate-workflow-status:
  runs-on: ubuntu-latest
  needs:
    - run-slow-succeeding-workflow
    - run-fast-failing-workflow
  if: always()  # Ensures this job runs even if dependencies fail
  steps:
    - name: Check Workflow Status from Job Results
      shell: bash
      run: |
        echo "Succeeding workflow result: ${{ needs.run-slow-succeeding-workflow.result }}"
        echo "Failing workflow conclusion: ${{ needs.run-fast-failing-workflow.conclusion }}"

        if [[ "${{ needs.run-slow-succeeding-workflow.result }}" == "success" && "${{ needs.run-fast-failing-workflow.conclusion }}" == "failure" ]]; then
          echo "✅ Conditions met: Succeeding job succeeded, failing job failed."
          exit 0  # Mark workflow as successful
        else
          echo "❌ Conditions NOT met. Marking workflow as failed."
          exit 1  # Explicitly fail the workflow
        fi
