name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print Full Repository Path
        run: 'echo "Repository: ${{ github.repository }}"'
        shell: bash
      
      - name: Run workflow using custom action
        uses: ./
        with:
          token: ${{ secrets.SINGING_STAGE_WORKFLOW_TOKEN }}
          repository: ${{ github.repository }}
          workflow: dispatched-workflow.yml
          ref: main
          inputs: |
            {
              "allow_major_change": false,
              "uuid": "${{ github.sha }}"
            }
