name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-slow-succeeding-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Slow Succeeding Workflow
        uses: ./
        with:
          token: ${{ secrets.SINGING_STAGE_WORKFLOW_TOKEN }}
          repository: ${{ github.repository }}
          workflow: dispatched-slow-succeeding-workflow.yml
          ref: main

          inputs: |
            {
              "uuid": "${{ github.sha }}-1"
            }
  run-fast-failing-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Fast Failing Workflow
        uses: ./
        with:
          token: ${{ secrets.SINGING_STAGE_WORKFLOW_TOKEN }}
          repository: ${{ github.repository }}
          workflow: dispatched-fast-failing-workflow.yml
          ref: main
          expected: 'failure'

          inputs: |
            {
              "uuid": "${{ github.sha }}-2"
            }